<a href="https://colab.research.google.com/github/rs-saran/S3-to-visualization/blob/main/TF_PT_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf
import torch

### 01. Tensors

In [7]:
#Basic Vector Handling

# Create tensors
vector1 = tf.constant([1.0, 2.0, 3.0]) #immuntable
a = tf.Variable([1.0, 2.0, 3.0]) #mutable
zeros1 = tf.zeros(3)
ones1 = tf.ones(3)
range_vector1 = tf.range(0, 5, delta=1)  # Similar to Python's range
print("Vector:", vector1)
print("Zeros:", zeros1)
print("Ones:", ones1)
print("Range:", range_vector1)


# Create constant tensors
vector = torch.tensor([1.0, 2.0, 3.0]) #mutable
zeros = torch.zeros(3)
ones = torch.ones(3)
range_vector = torch.arange(0, 5, step=1)  # Similar to Python's range
print("Vector:", vector)
print("Zeros:", zeros)
print("Ones:", ones)
print("Range:", range_vector)

Vector: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
Zeros: tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
Ones: tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)
Range: tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
Vector: tensor([1., 2., 3.])
Zeros: tensor([0., 0., 0.])
Ones: tensor([1., 1., 1.])
Range: tensor([0, 1, 2, 3, 4])


In [9]:
# Reshape a vector
matrix = tf.reshape(tf.range(6), (2, 3))
print("Matrix:\n", matrix)

# Transpose
transposed = tf.transpose(matrix)
print("Transposed Matrix:\n", transposed)


# Reshape a vector
matrix = torch.arange(6).reshape(2, 3)
print("Matrix:\n", matrix)

# Transpose
transposed = matrix.T  # Or matrix.transpose(0, 1)
print("Transposed Matrix:\n", transposed)

Matrix:
 tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32)
Transposed Matrix:
 tf.Tensor(
[[0 3]
 [1 4]
 [2 5]], shape=(3, 2), dtype=int32)
Matrix:
 tensor([[0, 1, 2],
        [3, 4, 5]])
Transposed Matrix:
 tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [13]:
# Broadcasting addition
a = tf.constant([1, 2, 3])
b = tf.constant([[10,20,30]])
result = a + b
print("Broadcasted Result:\n", result)

# Broadcasting addition
a = torch.tensor([1, 2, 3])
b = torch.tensor([[10], [20], [30]])
result = a + b
print("Broadcasted Result:\n", result)



Broadcasted Result:
 tf.Tensor([[11 22 33]], shape=(1, 3), dtype=int32)
Broadcasted Result:
 tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])


In [17]:
a = tf.constant([1.0, 2.0, 3.0])
b = tf.constant([4.0, 5.0, 6.0])

# Addition, subtraction, multiplication, and division
# add = tf.add(a, b)
# subtract = tf.subtract(a, b)
# multiply = tf.multiply(a, b)
# divide = tf.divide(a, b)

add = a + b
subtract = a - b
multiply = a * b
divide = a / b
print("Add:", add)
print("Subtract:", subtract)
print("Multiply:", multiply)
print("Divide:", divide)


Add: tf.Tensor([5. 7. 9.], shape=(3,), dtype=float32)
Subtract: tf.Tensor([-3. -3. -3.], shape=(3,), dtype=float32)
Multiply: tf.Tensor([ 4. 10. 18.], shape=(3,), dtype=float32)
Divide: tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float32)


In [16]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

# Addition, subtraction, multiplication, and division
add = a + b
subtract = a - b
multiply = a * b
divide = a / b
print("Add:", add)
print("Subtract:", subtract)
print("Multiply:", multiply)
print("Divide:", divide)


Add: tensor([5., 7., 9.])
Subtract: tensor([-3., -3., -3.])
Multiply: tensor([ 4., 10., 18.])
Divide: tensor([0.2500, 0.4000, 0.5000])


In [22]:
a = tf.constant([1.0, 2.0, 3.0])

# Sum, mean, and maximum
print("Sum:", tf.reduce_sum(a))
print("Mean:", tf.reduce_mean(a))
print("Max:", tf.reduce_max(a))


Sum: tf.Tensor(6.0, shape=(), dtype=float32)
Mean: tf.Tensor(2.0, shape=(), dtype=float32)
Max: tf.Tensor(3.0, shape=(), dtype=float32)


In [23]:
a = torch.tensor([1.0, 2.0, 3.0])

# Sum, mean, and maximum
print("Sum:", torch.sum(a))
print("Mean:", torch.mean(a))
print("Max:", torch.max(a))


Sum: tensor(6.)
Mean: tensor(2.)
Max: tensor(3.)


In [25]:
#inplace operations (present in torchwith _ suffix, not present in tf) #use cautiously could cause problem with gradient computations
import torch

# Create a tensor
a = torch.tensor([1.0, 2.0, 3.0])

# In-place addition
a.add_(1.0)  # Adds 1.0 to each element in-place
print("In-place addition:", a)

# In-place multiplication
a.mul_(2.0)  # Multiplies each element by 2 in-place
print("In-place multiplication:", a)


In-place addition: tensor([2., 3., 4.])
In-place multiplication: tensor([4., 6., 8.])


In [28]:

# Create a tensor
a = tf.Variable([1.0, 2.0, 3.0])

# Simulate in-place addition
a.assign_add([1.0, 1.0, 1.0])  # Add 1.0 to each element
print("Simulated in-place addition:", a)

# Simulate in-place multiplication
a.assign(a * 2.0)  # Multiply each element by 2
print("Simulated in-place multiplication:", a)


Simulated in-place addition: <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>
Simulated in-place multiplication: <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([4., 6., 8.], dtype=float32)>


In [31]:
# TensorFlow tensor to NumPy array
a = tf.Variable([1.0, 2.0, 3.0])
numpy_array = a.numpy()
print("NumPy array:", numpy_array)

# NumPy array to TensorFlow tensor
b = tf.convert_to_tensor(numpy_array)
print("TensorFlow tensor:", b)

# In-place changes
numpy_array[0] = 10  # Changes DO NOT reflect in the TensorFlow tensor
print("Modified NumPy array:", numpy_array)
print("Unchanged TensorFlow tensor:", b) #remains unchanged even if we used variable/constant in a


NumPy array: [1. 2. 3.]
TensorFlow tensor: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
Modified NumPy array: [10.  2.  3.]
Unchanged TensorFlow tensor: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [33]:
# PyTorch tensor to NumPy array
a = torch.tensor([1.0, 2.0, 3.0])
numpy_array = a.numpy()
print("NumPy array:", numpy_array)

# NumPy array to PyTorch tensor
b = torch.from_numpy(numpy_array)
print("PyTorch tensor:", b)

# In-place changes
numpy_array[0] = 10  # Changes reflect in the PyTorch tensor
print("Modified NumPy array:", numpy_array)
print("Modified PyTorch tensor:", b) #tensor and numpy array share same memory


NumPy array: [1. 2. 3.]
PyTorch tensor: tensor([1., 2., 3.])
Modified NumPy array: [10.  2.  3.]
Modified PyTorch tensor: tensor([10.,  2.,  3.])


### 02. Gradients

In [35]:
# Define a trainable variable
x = tf.Variable(3.0)

# Use GradientTape to compute the gradient
with tf.GradientTape() as tape:
    y = x**2 + 2 * x + 1  # Compute function y = x^2 + 2x + 1

# Compute dy/dx
dy_dx = tape.gradient(y, x)
print("Gradient:", dy_dx.numpy())  # Output: 8.0


Gradient: 8.0


In [36]:
# Define a trainable variable
x = torch.tensor(3.0, requires_grad=True)

# Compute function y = x^2 + 2x + 1
y = x**2 + 2 * x + 1

# Compute dy/dx
y.backward()
print("Gradient:", x.grad.item())  # Output: 8.0

Gradient: 8.0


In [37]:
x = tf.Variable(3.0)
z = tf.Variable(2.0)

with tf.GradientTape() as tape:
    y = x**2 + z**3

# Compute gradients
grads = tape.gradient(y, [x, z])
print("Gradient w.r.t x:", grads[0].numpy())  # Output: 6.0
print("Gradient w.r.t z:", grads[1].numpy())  # Output: 12.0


Gradient w.r.t x: 6.0
Gradient w.r.t z: 12.0


In [38]:
x = torch.tensor(3.0, requires_grad=True)
z = torch.tensor(2.0, requires_grad=True)

y = x**2 + z**3

y.backward()
print("Gradient w.r.t x:", x.grad.item())  # Output: 6.0
print("Gradient w.r.t z:", z.grad.item())  # Output: 12.0


Gradient w.r.t x: 6.0
Gradient w.r.t z: 12.0


In [39]:
#higher order gradient

x = tf.Variable(3.0)

with tf.GradientTape() as tape2:
    with tf.GradientTape() as tape1:
        y = x**3
    dy_dx = tape1.gradient(y, x)  # First derivative
d2y_dx2 = tape2.gradient(dy_dx, x)  # Second derivative

print("First Derivative:", dy_dx.numpy())  # Output: 27.0
print("Second Derivative:", d2y_dx2.numpy())  # Output: 18.0

x = torch.tensor(3.0, requires_grad=True)

y = x**3
dy_dx = torch.autograd.grad(y, x, create_graph=True)[0]  # First derivative
d2y_dx2 = torch.autograd.grad(dy_dx, x)[0]  # Second derivative

print("First Derivative:", dy_dx.item())  # Output: 27.0
print("Second Derivative:", d2y_dx2.item())  # Output: 18.0



First Derivative: 27.0
Second Derivative: 18.0
First Derivative: 27.0
Second Derivative: 18.0


In [40]:
# by default, gradients accumulate in PyTorch, while in TensorFlow, they don't unless explicitly handled.
x = torch.tensor(3.0, requires_grad=True)

# Compute gradients twice
y1 = x**2
y1.backward()  # Grad: 6.0

y2 = x**3
y2.backward()  # Grad: 27.0

print("Accumulated Gradient:", x.grad.item())  # Output: 33.0


Accumulated Gradient: 33.0


In [43]:
x = tf.Variable(3.0)

# Use separate tapes to accumulate gradients
with tf.GradientTape() as tape1:
    y1 = x**2
grad1 = tape1.gradient(y1, x)

with tf.GradientTape() as tape2:
    y2 = x**3
grad2 = tape2.gradient(y2, x)

# Accumulate manually
accumulated_grad = grad1 + grad2
print("Accumulated Gradient:", accumulated_grad.numpy())  # Output: 33.0


Accumulated Gradient: 33.0


In [46]:
#5. Stop Gradient
x = tf.Variable(3.0)
with tf.GradientTape() as tape:
    y = x**2
    z = tf.stop_gradient(y) * 3  # No gradient contribution from y
grad = tape.gradient(z, x)
print("Gradient:", grad.numpy())  # Output: 0.0

x = torch.tensor(3.0, requires_grad=True)
y = x**2
with torch.no_grad():  # No gradient contribution from y
    z = y * 3
z.backward()
print("Gradient:", x.grad)  # Output: None or 0


AttributeError: 'NoneType' object has no attribute 'numpy'



| Feature                  | TensorFlow                              | PyTorch                               |
|--------------------------|-----------------------------------------|---------------------------------------|
| Gradient Calculation     | `tf.GradientTape()`                    | `.backward()`                        |
| Gradient Accumulation    | Doesn't accumulate by default          | Accumulates by default               |
| Higher-Order Gradients   | Nested `GradientTape`                  | `create_graph=True`                  |
| Stop Gradient            | `tf.stop_gradient()`                   | `torch.no_grad()`                    |


### 03. Buliding Model Layers

In [49]:
# Define a Sequential model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(32, activation='relu', input_shape=(128,1)),  # Input layer
    tf.keras.layers.Dense(64, activation='relu'),                     # Hidden layer
    tf.keras.layers.Dense(10, activation='softmax')                   # Output layer
])

# Model summary
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                      │ (None, 128, 32)             │              64 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 128, 64)             │           2,112 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_8 (Dense)                      │ (None, 128, 10)             │             650 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,826 (11.04 KB)

 Trainable params: 2,826 (11.04 KB)

 Non-trainable params: 0 (0.00 B)

In [50]:
import torch.nn as nn

# Define a Sequential model
model = nn.Sequential(
    nn.Linear(128, 32),  # Input layer
    nn.ReLU(),           # Activation
    nn.Linear(32, 64),   # Hidden layer
    nn.ReLU(),
    nn.Linear(64, 10),   # Output layer
    nn.Softmax(dim=1)    # Activation for multi-class classification
)

# Print model architecture
print(model)


Sequential(
  (0): Linear(in_features=128, out_features=32, bias=True)
  (1): ReLU()
  (2): Linear(in_features=32, out_features=64, bias=True)
  (3): ReLU()
  (4): Linear(in_features=64, out_features=10, bias=True)
  (5): Softmax(dim=1)
)


In [51]:
class CustomModel(tf.keras.Model):
    def __init__(self):
        super(CustomModel, self).__init__()
        self.dense1 = tf.keras.layers.Dense(32, activation='relu')
        self.dense2 = tf.keras.layers.Dense(64, activation='relu')
        self.output_layer = tf.keras.layers.Dense(10, activation='softmax')

    def call(self, inputs):
        x = self.dense1(inputs)
        x = self.dense2(x)
        return self.output_layer(x)

# Create an instance of the model
model = CustomModel()


In [52]:
class CustomModel(nn.Module):
    def __init__(self):
        super(CustomModel, self).__init__()
        self.dense1 = nn.Linear(128, 32)
        self.dense2 = nn.Linear(32, 64)
        self.output_layer = nn.Linear(64, 10)
        self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        x = torch.relu(self.dense1(x))
        x = torch.relu(self.dense2(x))
        return self.softmax(self.output_layer(x))

# Create an instance of the model
model = CustomModel()


In [53]:
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(64, 64, 3)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

class ConvModel(nn.Module):
    def __init__(self):
        super(ConvModel, self).__init__()
        self.conv = nn.Conv2d(3, 32, kernel_size=3, activation='relu')
        self.pool = nn.MaxPool2d(kernel_size=2)
        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(32 * 31 * 31, 64)  # 31 = (input_dim - kernel + 1) / pool
        self.fc2 = nn.Linear(64, 10)
        self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        x = torch.relu(self.conv(x))
        x = self.pool(x)
        x = self.flatten(x)
        x = torch.relu(self.fc1(x))
        return self.softmax(self.fc2(x))

model = ConvModel()


/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


TypeError: Conv2d.__init__() got an unexpected keyword argument 'activation'

---


| **Use Case**                       | **Sequential API**                     | **Class-Based Model**                     |
|------------------------------------|----------------------------------------|------------------------------------------|
| **Simple Feedforward Networks**    | ✅                                      | ❌                                        |
| **Complex Architectures**          | ❌                                      | ✅                                        |
| **Dynamic Logic (e.g., Loops)**    | ❌                                      | ✅                                        |
| **Multiple Inputs/Outputs**        | ❌                                      | ✅                                        |
| **Custom Layers/Operations**       | ❌                                      | ✅                                        |
| **Layer Sharing**                  | ❌                                      | ✅                                        |
| **Ease of Use & Rapid Prototyping**| ✅                                      | ❌                                        |
| **Control Over Forward Pass**      | ❌                                      | ✅                                        |

---

In [54]:
# Why only forward function defined in Class and not backward?
# When you perform operations in the forward pass, the frameworks record a computation graph (a dynamic graph in PyTorch and a static/eager graph in TensorFlow).
#During backpropagation, the frameworks traverse this computation graph automatically to compute gradients using reverse-mode automatic differentiation (a.k.a. backpropagation).

In [55]:
#Names should be forward and call, should not be changed

In [66]:
@tf.custom_gradient
def custom_square(x):
    def grad(dy):
        return 2.5 * x * dy  # Define custom gradient, here dy indicates gradient coming from the next layer (L+1 -> L) during backproagation
    return tf.square(x), grad

class CustomLayer(tf.keras.layers.Layer):
    def call(self, inputs):
        return custom_square(inputs)

# Use the custom operation
x = tf.Variable([2.0])

with tf.GradientTape() as tape:
    y = CustomLayer().call(x)
grad = tape.gradient(y, x)
print(x,y,grad)  # Output: tensor([4.])

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.], dtype=float32)> tf.Tensor([4.], shape=(1,), dtype=float32) tf.Tensor([5.], shape=(1,), dtype=float32)


In [61]:
from torch.autograd import Function

class CustomSquare2(Function):
    @staticmethod
    def forward(ctx, x):
        ctx.save_for_backward(x)  # Save input for backward pass
        return x ** 2

    @staticmethod
    def backward(ctx, grad_output):
        x, = ctx.saved_tensors
        return 3 * x * grad_output  # Custom gradient logic

# Use the custom operation
x = torch.tensor([2.0], requires_grad=True)
y = CustomSquare2.apply(x)
y.backward()
print(x,y,x.grad)  # Output: tensor([4.])


tensor([2.], requires_grad=True) tensor([4.], grad_fn=<CustomSquare2Backward>) tensor([6.])


In [85]:
import torch
import torch.nn as nn
import torch.nn.init as init

class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(128, 64)
        self.fc2 = nn.Linear(64, 32)

        # Applying Xavier Uniform initialization
        init.xavier_uniform_(self.fc1.weight)
        init.xavier_uniform_(self.fc2.weight)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        return x

# Create a model and initialize weights
model = SimpleNN()
print(model)


SimpleNN(
  (fc1): Linear(in_features=128, out_features=64, bias=True)
  (fc2): Linear(in_features=64, out_features=32, bias=True)
)


In [88]:
import tensorflow as tf

class SimpleNN1(tf.keras.Model):
    def __init__(self):
        super(SimpleNN1, self).__init__()
        self.fc1 = tf.keras.layers.Dense(64, activation='relu', input_dim=128)  # First layer
        self.fc2 = tf.keras.layers.Dense(32, activation='relu')                  # Second layer
        self.fc3 = tf.keras.layers.Dense(10, activation='softmax')               # Output layer

    def call(self, inputs):
        x = tf.nn.relu(self.fc1(inputs))  # Apply ReLU after first layer
        x = tf.nn.relu(self.fc2(x))      # Apply ReLU after second layer
        return self.fc3(x)               # Return output

# Create the model instance
model = SimpleNN1()

# Use `build` with input shape or pass dummy input data
model.build((None, 128))  # Here (None, 128) means batch size can vary, input size is 128

# Now call model.summary()
model.summary()  # Batch size of None, input size of 128

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.10/dist-packages/keras/src/layers/layer.py:391: UserWarning: `build()` was called on layer 'simple_nn1_5', however the layer does not have a `build()` method implemented and it looks like it has unbuilt state. This will cause the layer to be marked as built, despite not being actually built, which may cause failures down the line. Make sure to implement a proper `build()` method.
  warnings.warn(


Model: "simple_nn1_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_32 (Dense)                     │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_33 (Dense)                     │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_34 (Dense)                     │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [83]:
# Pass a batch of data (e.g., with shape (32, 128)) to the model
dummy_input = tf.random.normal((32, 128))
model(dummy_input)

# Now call model.summary()
model.summary()

Model: "simple_nn_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_26 (Dense)                     │ (1, 64)                     │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_27 (Dense)                     │ (1, 32)                     │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_28 (Dense)                     │ (1, 10)                     │             330 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 10,666 (41.66 KB)

 Trainable params: 10,666 (41.66 KB)

 Non-trainable params: 0 (0.00 B)

In [87]:
#Optimizers: just how to adjust the parameters based on gradient

import torch.optim as optim

model = SimpleNN()  # Assuming a model is defined

optimizer = optim.SGD(model.parameters(), lr=0.01)


In [90]:
model = SimpleNN1()
# Compile the model with the Adam optimizer
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


###Training, testing and inference loops